[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
web-sys = "0.3.61"
yew = { version = "0.20.0", features = ["csr"] }
gloo-net = "0.2"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"
serde_json = "1.0.96"
